lsi: false
safe: true

title: "reddust's blog-y thing"
author: reddust

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
